== O čem je Fedora
=== Pro koho je?

Fedora v{nbsp}edici _Workstation_ cílí na uživatele, jejichž primárním zájmem je tvůrčí práce, ať už se jedná o{nbsp}vývoj nebo jiné činnosti. Nabízí odladěné prostředí _GNOME{nbsp}3_ a spektrum aplikací jako jsou pro vývojáře nástroje _DevAssistant_ nebo nově _Builder_, různé aplikace pro virtualizaci (_Boxes_), správu kontejnerů (_Docker_) a dalších. Znamená to, že Fedora rezignuje na běžného uživatele a opouští ho? Ne, Fedoru lze stejně tak dobře použít i pro multimediální účely, mezi které můžeme počítat i střih videa (_PiTiVi_), nebo práci s{nbsp}bitmapovou (_GIMP_) a vektorovou (_Inkscape_) grafikou. V{nbsp}určitém smyslu je tak Fedora lepším operačním systémem i pro běžného uživatele, než byla kdy dříve.  

=== Otevřenost

Fedora je linuxový operační systém s{nbsp}desetiletou tradicí vyvíjený komunitou, tedy profesionálními vývojáři a dobrovolníky bez rozdílu. Vždy obsahovala a bude obsahovat jen svobodný, čili takový software, který je open source a může být volně šířen, upravován a používán za libovolným účelem. Fedora neobsahuje software, na který byste si nemohli "`sáhnout`" na úrovni zdrojového kódu. Zároveň ale nijak neomezuje software, který si do systému nainstalujete. Ať již jako jednotlivý balík nebo formou repozitáře (zdroje software, viz kapitola _Instalace nového software_). Chcete _Google Chrome_? Budete ho mít. Ale i bez toho naleznete v{nbsp}repozitářích Fedory takřka dvacet tisíc balíků obsahujících nejrůznější aplikace a knihovny. Není to ale jen o{nbsp}licenční čistotě. Fedora důsledně ctí patentové právo v{nbsp}oblasti software (jakkoliv je v{nbsp}rámci EU méně relevantní). Při nasazení Fedory v{nbsp}komerčním i jiném prostředí máte jistotu, že jednáte v{nbsp}souladu se zákonem.

=== Bezpečnost a soukromí

Vývoj Fedory má svá jasná pravidla a bezpečnost je priorita. Ve Fedoře probíhá testování jako u{nbsp}kteréhokoli jiného významného softwarového produktu. Navíc se Fedora každých několik let stává základem, na kterém staví firma Red Hat svůj linuxový operační systém s{nbsp}komerční podporou -- Red{nbsp}Hat Enterprise Linux{nbsp}(RHEL). Stejná firma také platí mnoho vývojářů zapojených do projektu Fedory a vlastní ochranné známky s{nbsp}Fedorou související. Podpora Fedory, která se počítá od data vydání aktuální verze systému po vydání verze další plus jeden měsíc (což při dodržení šestiměsíčního cyklu činní třináct měsíců), pak důsledně zahrnuje bezpečnostní záplaty. A{nbsp}nejen to. Po celou dobu podpory jsou do Fedory začleňovány nové verze jádra. Uplatníme-li hrubou zkratku, že nová verze jádra se rovná novému podporovanému hardware, máme tu další plus bod. Fedora zároveň neobsahuje žádné programy, které by bez vašeho vědomí odesílaly jakékoliv informace. Nikdy. Fedora vás nešmíruje, naopak maximálně ctí vaše soukromí.

=== V{nbsp}čele pelotonu

Do Fedory se dostává velké množství nového softwaru, často je tak Fedora první (nebo jeden z{nbsp}prvních) operační systém, který daný software nasadí. Fedora je běžně místem, jakýmsi podhoubím, kde k{nbsp}vývoji takových programů dochází. Otevřený software je o{nbsp}spolupráci, lidé zapojení do Fedory se často intenzivně věnují i práci mimo samotný projekt. Nečekají, až někdo něco vyvine a oni to pak budou moci zahrnout do Fedory, ale aktivně se podílí na vývoji přímo u{nbsp}zdroje, přímo u{nbsp}konkrétního projektu, ať už spolu s{nbsp}dalšími vývojáři primárně pracujícími na jiných linuxových operačních systémech nebo s{nbsp}dalšími zcela nezávislými vývojáři. Časem se takové programy běžně stávají standardy ve většině linuxového světa. Uživatel Fedory tak jde s{nbsp}dobou nebo má i předstih. A{nbsp}taková Fedora je. Progresivní. Inovativní. V{nbsp}čele.

