== What is Fedora about
=== Who is it for?

Fedora in the _Workstation_ edition aims at users who use computers to primarily create, no matter if it's software development or other creative activities. It offers the{nbsp}_GNOME{nbsp}3_ environment and a variety of applications such as developer tools _DevAssistant_ or newly _Builder_, apps for virtualization (_Boxes_), container management (_Docker_) etc. Does that mean that Fedora has given up satisfying needs of an average user? No, Fedora is also suitable for multimedia tasks such as video editing (_PiTiVi_) or bitmap (_GIMP_) and vector (_Inkscape_) graphics editing. In a sense, Fedora is a better operating system for an average user than it ever was.

=== Openness

Fedora is a Linux operating system that has a history of more than 10 years of development by a community which is a group of both professional developers and volunteers. It has always included and will include only open source software. That's software which has available source code, can be distributed, modified, and used for any purpose. Fedora doesn't include software you couldn't "touch" on the source code level. On the other hand, it doesn't prevent you from installing any software you want. No matter if it's in the form or an individual package or a repository (see the _Installing new software_ chapter). Do you want _Google Chrome_? You'll have it. But even without 3rd-party software, you'll find more then 20 thousand packages for Fedora which represent various apps, extensions, and libraries. It's not only about license purity. Fedora also respects the software patent law (even though it may not be relevant in some parts of the world). You can be sure that you don't break law by using Fedora.

=== Security and Privacy

Development of Fedora has clear rules and security is a priority. Fedora is tested like any other significant software product. Moreover Fedora is a base for Red Hat Enterprise Linux which is offered with commercial support. Red Hat also pays many developers, who are involved in the Fedora Project, and owns Fedora trademarks. Fedora community support, that lasts for two release cycles plus one month (which is 13 months considering Fedora has a 6-month release cycle), strictly includes security fixes. And not only that. Fedora also updates to newer versions of the Linux kernel. Simply put, newer kernel versions mean new hardware support which is another plus for Fedora. It also doesn't include any programs that would send any sensitive data out without your approval. Never. Fedora doesn't spy on you, it respects your privacy.

=== At the Front of the Pack

Fedora integrates a lot of new software, it's often the first (or one of the first) operating systems that adopts the new technology. Fedora is very often where new technologies are being developed. Open source software is about collaboration and people who are involved in Fedora are very often active in other projects, too. They don't wait until someone else develops it and they can then include it in Fedora, but actively participates in upstream projects where they collaborate with participants from other Linux operating systems or independent developers. It's common that such software then becomes de facto standard in the Linux world. Fedora users keep fingers on the pulse and are ahead of others. That's what Fedora is like. Progressive, innovative, at the front of the pack.
