== Where to look for further Information

This handbook exists to help you get started with Fedora. But, what can you do if you encounter a problem that you can't quickly solve? A good rule of thumb is to remember that any problem you're encountering has probably already been solve was probably solved by somebody else before you. Here is where to look for solutions:

* link:http://fedoraforum.org[fedoraforum.org] -- English language forums with very large user base and long history of solved problems.
* link:http://fedoramagazine.org[fedoramagazine.org] -- articles from Fedora world. This also includes information about new applications and annoucements.

=== What to do if you encounter a bug
It is possible that you will encounter a bug. What then? Fedora uses Bugzilla, a bug tracker, provided by Red Hat. It is available online at link:http://bugzilla.redhat.com[bugzilla.redhat.com]. Bugs are required to be reported in English.

There is a also a tool in Fedora called ABRT. ABRT allows anyone to report bugs or errors by just agreeing to share the details with the Fedora Project. Even if you don't have time to contribute by fixing the bug, be sure to let us know about it by using ABRT.

=== Other Fedora Editions
Unline many other generic Linux operating systems, Fedora consists of 3 main editions. This guide describes the Workstation edition. There are also _Server_ and _Cloud_ Editions. The _Server_ edition is designed for server uses and features applications like Cockpit which allows for easy remote management of servers through a web browser and the administration of server roles through _Rolekit_. The _Cloud_ edition is a minimal version of Fedora optimized for deploying containers. There are multiple Fedora Cloud images opitimized for use in environments like _OpenStack_, _VirtualBox_ and others.

=== Fedora Spins
Everything in this guide is about the default Fedora _Workstation_ edition. This version uses _GNOME{nbsp}3_ and the _GNOME Shell_. However, there are alternatives to Gnome. Fedora spins, which are alternative software builds of Fedora exist for other window managers. So, if you want to to use _KDE Plasma Desktop_, you'll find a spin built image for that. _Xfce_? _LXDE_? We have prepared images for everything.

But we don't have to stop with Fedora spins. Nowadays the ARM architecture is popular. It is the most used mobile platform and is a significant platform for development boards, such as the Banana Pi, BeagleBone, and the Raspberry Pi. There are images built to run on these kinds of systems too in the form of server versions or minimal install images.
