== Chcete vědět víc?
=== Kam se podívat dál?

Naše příručka má skromné ambice, ale co když narazíte na problém, který nejste schopni rychle vyřešit? Základní pravidlo zní: problém, který řešíte, už takřka jistě řešil někdo před vámi. Kam se tedy podívat?

* link:http://mojefedora.cz[mojefedora.cz] -- z{nbsp}českých webů ve vztahu k{nbsp}Fedoře zásadní stránky (a univerální rozcestník). Obsahuje množství článků, tipů a dalších informací.

* link:http://wiki.mojefedora.cz[wiki.mojefedora.cz] -- příručka o{nbsp}Fedoře, na které mnoho lidí odvedlo obrovské množství práce. Mnoho návodů, které hledáte, budou právě zde.

* link:http://forum.mojefedora.cz[forum.mojefedora.cz] -- fórum v{nbsp}českém jazyce hodící se vždy, když nejste schopni problém vyřešit sami nebo když sami chcete nabídnout svou pomoc.

* link:http://fedoraforum.org[fedoraforum.org] -- fórum v{nbsp}anglickém jazyce s{nbsp}rozsáhlou uživatelskou základou a dlouhou historií řešených problémů. Nyní už byste mohli být v{nbsp}cíli.

* link:http://fedoramagazine.org[fedoramagazine.org] -- články o{nbsp}dění kolem Fedory. Nové aplikace a oznámení.

=== Co když narazím na chybu?

Je docela možné, že se dostanete do situace, kdy narazíte na chybu zcela novou. Co pak? Fedora používá bugzillu společnosti Red Hat, která je dostupná z{nbsp}adresy link:http://bugzilla.redhat.com[bugzilla.redhat.com]. (Nutno podotknout, že nezbytností při hlášení chyb je angličtina, alespoň na základní úrovni.) Není to ale jediná možnost, jak chybu ohlásit. Ve Fedoře je dostupný nástroj ABRT. Budeme-li citovat klasický snímek, pak daný nástroj vystihuje spojení _každý přispívá podle svých možností_ a ABRT koná přesně v{nbsp}tom duchu.

=== Další edice Fedory

Zde se dostáváme k{nbsp}věcem, ve kterých se Fedora odlišuje od obecného spektra linuxových operačních systémů. Fedora doznala své podoby ve třech hlavních edicích. Už dříve popsaná je edice _Workstation_, dále pak tu máme edice _Server_ a _Cloud_. Pojďme na ně. U{nbsp}edice _Server_ lze vyzdvihnout aplikace jako Cockpit sloužící pro vzdálenou správu běžících serverů prostřednictvím webového prohlížeče nebo administraci serverových rolí přes Rolekit. U{nbsp}edice _Cloud_ pak máme k{nbsp}dispozici minimalistickou verzi Fedory, která umožňuje akorát nasazení kontejnerů. A{nbsp}že existuje hned několik obrazů Fedory Cloud připravených pro nasazení v{nbsp}prostředí _OpenStack_, _VirtualBox_ a dalších.

=== Fedora a spiny

Vše, co dosud padlo ve vztahu k{nbsp}Fedora _Workstation_, se týkalo výchozího cílení toho operačního systému, jehož desktopovým prostředím je _GNOME{nbsp}3_ a jeho _GNOME Shell_. Co když se ale chceme rozhlédnout dále? Ve Fedoře existují tzv. spiny, čili připravené instalační obrazy se specifickým cílením. Jste zvyklí na _KDE Plasma_? Je tu _KDE Plasma Desktop_. _Xfce_? _LXDE_? Pro vše tu jsou připravené obrazy. Ale ani u{nbsp}Fedora spinů se nemusíme zastavit. V{nbsp}dnešní době je velmi aktuální procesorová architektura ARM (nejčastější mobilní platforma, platforma pro různé vývojové desky à la Banana Pi, BeagleBone, nebo v{nbsp}případě Fedora Remixu i Raspberry Pi). Stejně jako některé další linuxové operační systémy i Fedora má pro tuto architekturu připravené řešení ve formě jak serverové verze, tak minimálního instalačního obrazu pro obecné použití.
